### ISSUE TITLE
Some PR workflows can't run successfully from user forks

### ISSUE THREAD

**Issue by tevoinea** [microsoft/component-detection#10]
For security reasons, workflows running from forks only have read permissions. The snapshot verification workflow requires reading a private repo which will fail on PRs created from user forks (see #9 as an example).

We need to remove the dependency on the componentdetection-verification repo and the `GH_Private_Repo_Pat` secret from workflows which run on PR events. It's ok to keep `GH_Private_Repo_Pat` for release workflows since those should never be run from a fork.

**Comment by JamieMagee** [comment]
Closed since we removed our dependency the verification repo.
