### ISSUE TITLE
Update to .NET 6.0

### ISSUE THREAD

**Issue by blowdart** [microsoft/component-detection#107]
As .NET 6 is an LTS the countdown for 3.1's death started on its release.

After Dec 3, 2022 .NET 3.1 will no longer be supported or patched.

**Comment by JamieMagee** [comment]
This work is in-progress in #76, but currently blocked by downstream projects. I'm working with downstream projects to figure out a timeline.

@blowdart mentioned there are some people on the dotnet team that could help get those projects up-to-date. I don't think we're at the stage where we need the assistance, but maybe in the near future, depending on what those projects reply.

**Comment by cobya** [comment]
The blocker our team had internally for this was resolved last week. @JamieMagee will hopefully be taking a look at this change later this week.

**Comment by JamieMagee** [comment]
Resolved in #288
