### ISSUE TITLE
Support pnpm 9

### ISSUE THREAD

**Issue by CraigMacomber** [microsoft/component-detection#1148]
Support pnpm lock file format 9.0 used by pnpm 9.

[Pnpm 8 is supported until April 2025](https://github.com/pnpm/pnpm/security), so for pnpm to remain supported, support for pnpm 9 should land enough before that to allow users to migrate.

**Comment by CraigMacomber** [comment]
pnpm has provided a 379 day window to migrate from pnpm 8 to pnpm 9 before security patches will no longer be provided. Over 25% of this time has now passed. I'm glad to see work on this is considered "ready" and I hope it gets implemented soon.

**Comment by CraigMacomber** [comment]
About 40% of the time-window for migrating from pnpm 8 to 9 has passed. "Status" has not changed since my last post.

pnpm 9 has had 23 stable releases: even though pnpm 8 is still getting security patching, it would be great to be able to move onto pnpm 9 and take advantage of all that new development work.

Is there any estimate of when pnpm 9 support will land?

**Comment by CraigMacomber** [comment]
Over 60% support window for pnpm 8 to allow migration to 9 has passed, and component-detection still does not support pnpm 9.

There have been no comments to this issue from the maintainers. There is a [PR](https://github.com/microsoft/component-detection/pull/1283) to add support, but its failing on CI and hasn't been touched in over a month.

Would it be possible to get an estimate of when pnpm 9 support will land? Maybe this work could be prioritized as a security item?

**Comment by FernandoRojo** [comment]
Hi @CraigMacomber, We got held up with some deployment freezes but I will be merging this and deploying today!
