### ISSUE TITLE
IgnoreDirectories from ADO task no longer works

### ISSUE THREAD

**Issue by jchen351** [microsoft/component-detection#1238]
Hi,
We are actively using the 
` - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0` ADO task as required by Micrsoft. But recently, we found the issues were reported from the directory that supposed to be ignore under `inputs:ignoreDirectories`. So, I wonder has the behavior of `IgnoreDirectories`change. 

Here is our usage of [IgnoreDirectories](https://github.com/microsoft/onnxruntime/blob/af18824f430225330ca58dd9a5a08bdc57900955/tools/ci_build/github/azure-pipelines/templates/component-governance-component-detection-steps.yml#L30).

**Comment by FernandoRojo** [comment]
Issues in the ADO task fall under the internal task code, hosted separately.

You can find links for who to contact to receive help with the Task execution in the first few lines of the logs for the task run.
