### ISSUE TITLE
pip detection is skipped

### ISSUE THREAD

**Issue by bebound** [microsoft/component-detection#1243]
Pip detection hasn't been working recently.

According to the log, pip detection is skipped due to the `PipReportOverrideBehavior` env.
```
Skipping pip report due to invalid PIP_INDEX_URL.

PipReport: Found PipReportOverrideBehavior environment variable set to Skip. Skipping pip detection for 'D:\a\_work\1\s\requirements.txt'.
PipReport: Found PipReportOverrideBehavior environment variable set to Skip. Skipping pip detection for 'D:\a\_work\1\s\tools\setup.py'.
PipReport: Found PipReportOverrideBehavior environment variable set to Skip. Skipping pip detection for 'D:\a\_work\1\s\src\azure-cli\setup.py'.
PipReport: Found PipReportOverrideBehavior environment variable set to Skip. Skipping pip detection for 'D:\a\_work\1\s\src\azure-cli-core\setup.py'.

│ PipReport         │ 2.3 seconds       │ 0                 │ 0                │
```
But I never set it. Why is this happening?

Here is the pipeline: https://github.com/Azure/azure-cli/blob/dev/azure-pipelines.yml

![image](https://github.com/user-attachments/assets/d7eb3e26-4d7a-41f8-8b1a-650050f3b5ae)

Ref: https://dev.azure.com/azclitools/public/_build/results?buildId=188073&view=logs&jobId=6f58747d-d468-56ca-0c09-7f5002273949&j=cc450d3b-3730-5e93-ae49-fca8cec7e4c0&t=01e6af79-ce5b-5da1-8753-5e40641f3cc3

**Comment by pauld-msft** [comment]
Internal microsoft issue, please open support request through internal channels following documentation at `aka.ms/cgdocs`
