### ISSUE TITLE
Add PNPM 6 support

### ISSUE THREAD

**Issue by grvillic** [microsoft/component-detection#17]
## Context

Detector scans PNPM 5 properly and picks up all dependencies as expected, same can't be said for PNPM 6. It seems that PNPM 6 is having silent failures when parsing `pnpm-lock.yaml` files, hence not only it doesn't pick up any dependency, but it makes it hard to realize the lack of coverage.

## Problem

- Lack of PNPM 6 Support
- Silent failures

Error log:
`LogFailedReadingFile logged SyntaxErrorException: (Line: 20485, Col: 135, Idx: 618058) - (Line: 20485, Col: 139, Idx: 618062): While scanning a plain scalar, find unexpected ':'`

## Solution

Add support for PNPM 6 detection and parsing

**Comment by cobya** [comment]
One of the potential issues I've found while investigating this is the use of github URLs in pnpm-lock.yaml files, ex:
```
"github.com/xmldom/xmldom/c568938641cc1f121cef5b4df80fcfda1e489b6e"
"github.com/faisalil/react-native-mock/ca38d5e1a922278de30fcf461d2eacd0b16a6363_react-native@0.62.2"
"github.com/joonhocho/react-native-android-action-sheet/f7436395ffb41e23a7770de18601d703913b5a95"
```

**Comment by cobya** [comment]
Closing in favor of #503
