### ISSUE TITLE
Do not log build warning for `npm` malformed files. 

### ISSUE THREAD

**Issue by JamieMagee** [microsoft/component-detection#199]
[`resolve`](https://www.npmjs.com/package/resolve) is used quite broadly in the Node.js ecosystem. In their published bundle, they include a [malformed `package.json`](https://github.com/browserify/resolve/blob/main/test/resolver/malformed_package_json/package.json). Whenever we encounter this file we log a warning. This is causing an excessive amount of warnings.

We should handles this more gracefully.

https://github.com/microsoft/component-detection/blob/a6205c0a190b9966031d6a7b08b9e78897f2528e/src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentDetector.cs#L68

https://github.com/microsoft/component-detection/blob/a6205c0a190b9966031d6a7b08b9e78897f2528e/src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentDetectorWithRoots.cs#L194

**Comment by mastrzyz** [comment]
Yeah we face this issue ourselves, there are a lot of warnings in our build system due to this. We want our build timeline to be as clean as possible, otherwise all warnings will be ignored if we spam 10 warnings every build.
