### ISSUE TITLE
Migrate from `ActionBlock` to `Channels`

### ISSUE THREAD

**Issue by JamieMagee** [microsoft/component-detection#234]
Recommended after speaking with @dfederm 

References:
- [An Introduction to `System.Threading.Channels`][1]
- [C# Job Queues][2]

[1]: https://devblogs.microsoft.com/dotnet/an-introduction-to-system-threading-channels/
[2]: https://michaelscodingspot.com/c-job-queues-with-reactive-extensions-and-channels/

**Comment by melotic** [comment]
We cannot use channels as each only one of the channel's reader will receive the message, so we would need multiple channels.

We need to be able to broadcast the message to all consumers, which the curent `System.Threading.Channels` does not support.
