### ISSUE TITLE
Python: Log output of distutils execution in case of failure

### ISSUE THREAD

**Issue by jenshnielsen** [microsoft/component-detection#242]
It would be nice if the stderr of executing `import distutils ...` [here](https://github.com/microsoft/component-detection/blob/main/src/Microsoft.ComponentDetection.Detectors/pip/PythonCommandService.cs#L58)
was logged in the case of a failure. 

E.g. in my usecase this failed due to an import in setup.py not being present in the env that component-detection is running in but that error was silent and setup.py simply ignored

AB#2140981

**Comment by cobya** [comment]
This will be handled in conjuction with #108

**Comment by cobya** [comment]
Resolved with #1129.
