### ISSUE TITLE
Is there a way to have scan manifest printed to stdout ?

### ISSUE THREAD

**Issue by sbs2001** [microsoft/component-detection#246]
This would make https://github.com/microsoft/component-detection/pull/220 far more usable.

**Comment by JamieMagee** [comment]
Not currently. We print a summary to stdout, but I can see why you'd want just the manifest. It means you don't have to mount a volume to the container.

**Comment by sbs2001** [comment]
Yes exactly. This would also make it easy to use the tool in scripts.

**Comment by sbs2001** [comment]
For now I'm using this hacky way to acheive this:
```
docker run -v /app:/scan ms_cd scan --Verbosity=Quiet --SourceDirectory /scan --ManifestFile=/dev/stdout 
```
