### ISSUE TITLE
Remove dependency on PackageUrl

### ISSUE THREAD

**Issue by dfederm** [microsoft/component-detection#25]
There is a dependency on this package: https://www.nuget.org/packages/PackageUrl/

It has 6k downloads total, a broken link to the source, has exactly 1 version, and this is the only package produced by this person.

This doesn't seems like a very trustworthy package we should be depending on.

**Comment by JamieMagee** [comment]
Those are all good points, and they are things I think we should prioritise upstream. Despite its flaws, that package is the official NuGet package.

There is currently an open issue to fix up the NuGet release process[^1], and an open PR to implement this[^2].

Let me followup with upstream and see if we can get those issues fixed 👍 

It's also interesting to note that the OpenSSF also depends on this package[^3]

[^1]: https://github.com/package-url/packageurl-dotnet/issues/6
[^2]: https://github.com/package-url/packageurl-dotnet/pull/7
[^3]: https://github.com/ossf/Project-Security-Metrics/blob/d104477709fe49b8b08441fab21c4eb45fcacba8/src/ingestion/MetricAPI.csproj#L11

**Comment by JamieMagee** [comment]
Marking this as blocked for now while we wait for a response from upstream[^3]

[^3]: https://github.com/package-url/packageurl-dotnet/pull/7#issuecomment-997093682

**Comment by JamieMagee** [comment]
Closed in #71
