### ISSUE TITLE
Publish to nuget.org

### ISSUE THREAD

**Issue by JamieMagee** [microsoft/component-detection#26]
Currently our packages are only published to our GitHub NuGet feed[^1]. To make is easier for users to find and consume our packages we should publish our packages to nuget.org.

We should follow Microsoft best practices for creating NuGet packages, including package signing, before publishing to nuget.org

[^1]: https://github.com/orgs/microsoft/packages?repo_name=component-detection

**Comment by edgarrs** [comment]
@JamieMagee , is this something you can prioritize to get it done soon? The SBOM OSS project needs to use a public ADO feed to be able to consume the Component Detectors packages
@aasim , @daneshbadlani

**Comment by JamieMagee** [comment]
I was out at a conference last week, but I will try and get this wrapped up this week.

**Comment by edgarrs** [comment]
@JamieMagee , any chance this might happen soon?
@daneshbadlani

**Comment by JamieMagee** [comment]
We've created the MicrosoftOpenSourceEngineeringTeam[^1] organization, and reserved the `Microsoft.ComponentDetection` and `Microsoft.ComponentDetection.*` package namespaces.

[^1]: https://www.nuget.org/profiles/MicrosoftOpenSourceEngineeringTeam

**Comment by JamieMagee** [comment]
We're currently blocked on ESRP signing https://dev.azure.com/msazure/ESRPSignOnboarding/_workitems/edit/15434568

**Comment by JamieMagee** [comment]
Component Detection is now available on nuget.org https://www.nuget.org/packages/Microsoft.ComponentDetection
