### ISSUE TITLE
Maven Detector should take into account dependency scope

### ISSUE THREAD

**Issue by grvillic** [microsoft/component-detection#29]
## Context
Dependencies in maven has different scopes. These scopes defined where the dependency is going to be provided or how the
dependency is going to be used. For example, the scope "provided" define that the dependency is going to be provided at runtime, this is pretty common when working on cloud applications where the cloud environment is the one that provides dependencies like Spark. Another scope is "test" that defined that the dependencies are going to be used for testing purposes, we could consider flagging these dependencies like "development dependencies"

## Solution
Consider the scopes when detecting the component this could help to describe how the dependency is going to be used.
More about scopes: https://www.baeldung.com/maven-dependency-scopes

**Comment by jcfiorenzano** [comment]
The maven detector takes into account scopes, today the only scope that we are considering is "test", where dependencies in this scope are marked as dev dependencies. We are in the middle of an investigation to evaluate how the provided scope should be treated.

**Comment by cobya** [comment]
Resolved with #87
