### ISSUE TITLE
Different python version results in different  result

### ISSUE THREAD

**Issue by Fallen-Tiger** [microsoft/component-detection#313]
when i use **python3**  to execute  **setup.py**,  result is  **[]**   ,but when i use  **python2.7**  ,the result is **None**.
So   component detection will  visit  the  website "**https://pypi.org/pypi/None/json**",  and this wheel  depend many other  packages。
It  will  include  many  unexpected  packages  of  None.

**Comment by JamieMagee** [comment]
Can you share a minimal `setup.py` to reproduce the bug?

**Comment by Fallen-Tiger** [comment]
setup.py:

import setuptools
setuptools.setup(
    name="my-test-package",
    version="1.0",
    zip_safe=True,
)

environments: python2.7.5 , centos7.9 ,  .net6.0.401
Executed command  ： python -c "import distutils.core; setup=distutils.core.run_setup('setup.py'); print(setup.install_requires)"
result:None
