### ISSUE TITLE
IPyPiClient response caching strategy should be improved

### ISSUE THREAD

**Issue by cobya** [microsoft/component-detection#35]
Within [microsoft/component-detection/IPyPiClient.cs at main](https://github.com/microsoft/component-detection/blob/main/src/Microsoft.ComponentDetection.Detectors/pip/IPyPiClient.cs#L76), the current caching implementation is simply a ConcurrentDictionary that will cache all of a PyPi responses's data to be used in case the dependency is found again later. However, in repositories with large Python package lists, this has a potential to allocate more memory than can be allocated in resource constrained environments.

The caching strategy within the client should be improved so that large Python dependency graphs can be generated using less allocated memory. Potential improvements such as migrating to an Least Recently Used cache should be investigated.

**Comment by JamieMagee** [comment]
Just gonna drop this link for future reference: https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.imemorycache?view=dotnet-plat-ext-6.0

**Comment by cobya** [comment]
With #80, I am close to closing this issue. We will perform some validation across Microsoft internally to verify the new caching functionality is working as expected and then update this issue.
