### ISSUE TITLE
%temp%\GovCompDisc_Log_(stamp).log naming conflicts fail concurrent builds

### ISSUE THREAD

**Issue by trevors20** [microsoft/component-detection#403]
The SBOM generator is failing in our concurrent builds due to the log file being the same name.
Here is an example of what I'm seeing in our binlog:

![image](https://user-images.githubusercontent.com/49179298/211615483-2f4ac952-e6f3-4871-a2a0-e92a54fb995f.png)

We have the fix for [Issue#134](https://github.com/microsoft/sbom-tool/issues/134) but we are still seeing concurrent issues when running the SBOM tool.

Is it possible to update the code to have a more unique value in it?  Like, a process id or a guid?
Please let me know if I can provide any more details.

**Comment by JamieMagee** [comment]
We discussed this internally and we're going to add a GUID part to the log file name, but retain the timestamp part as well, to allow for sorting. We can't switch to GUIDs entirely, as the GUID type in .NET is a UUIDv4, which is totally random[^1]

[^1]: https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_(random)
