### ISSUE TITLE
Go CLI detector should correctly use .gitconfig to ssh to private repos

### ISSUE THREAD

**Issue by annaowens** [microsoft/component-detection#511]
The Go CLI detector throws the following error when attempting to run `go list -m -json all` on a private repository:

```
##[error]Go CLI command "go list -m -json all" failed with error: go list -m: github.com/{repo-name}: invalid version: git ls-remote -q origin in /root/go/pkg/mod/cache/vcs/{xxx}: exit status 128:
	fatal: could not read Username for '[https://github.com'](https://github.com%27/): terminal prompts disabled
```

It appears that we are not authenticating properly when attempting to ssh to read private repositories. We should use the `.gitconfig` to authenticate (or find another way to handle authentication properly).

**Comment by pathuang-sia** [comment]
Is there any update on a potential fix for this error?

**Comment by pathuang-sia** [comment]
@melotic yes, here is an [example run](https://dev.azure.com/msazure/msk8s/_build/results?buildId=75906933&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=833edf1b-3669-5dbb-11e6-ee7d22230825) from the pipeline [here](https://dev.azure.com/msazure/msk8s/_build?definitionId=256528&_a=summary)

**Comment by melotic** [comment]
> @melotic yes, here is an [example run](https://dev.azure.com/msazure/msk8s/_build/results?buildId=75906933&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=833edf1b-3669-5dbb-11e6-ee7d22230825) from the pipeline [here](https://dev.azure.com/msazure/msk8s/_build?definitionId=256528&_a=summary)
> 
> However in [one of our latest runs](https://dev.azure.com/msazure/msk8s/_build/results?buildId=76731246&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=833edf1b-3669-5dbb-11e6-ee7d22230825), it seems like the go cli is not even found in the container

Thanks!

From what I can tell, this issue bit more nuanced than just using the `.gitconfig`. Go will use the `.gitconfig`, but the issue in your case is the build happens in a container, with the proper git authorization _inside_ the container.

CG then scans the build _outside_ the container, so auth fails. I think we need to sync with OneBranch to scan inside the container.

@JamieMagee, do you think this is correct?

**Comment by melotic** [comment]
This is not a CD issue as mentioned above. Will re-open if otherwise.
