### ISSUE TITLE
Be resilient to new lockfile formats

### ISSUE THREAD

**Issue by JamieMagee** [microsoft/component-detection#514]
Currently we're not handling updates in lockfile versions or formats very gracefully. Sure, we catch the exception that is thrown, but it's not obvious that someone is using a new version of a tool. See #503 or #476

**Comment by melotic** [comment]
I think a solution to this would be to add telemetry to each detector that has a lockfile version. We'd just need to send a record with the lockfile version, and the detector type.

Then, we could configure Application Insights to [generate an alert](https://learn.microsoft.com/en-us/azure/azure-monitor/alerts/alerts-types#log-alerts) when it detects a new version.

We would need a query sort of like this one to find the maximum lockfile version per detector. If we add the telemetry, we can then fine-tune this query.

```kusto
let timeRange = ago(6h);
let lookBack = ago(14d);
let latestLockfileVersions = customEvents
| where timestamp > lookBack
| where name == "LockfileVersion"
| extend Props = parse_json(customDimensions)
| extend Detector = Props['Detector'], LockfileVersion = toint(Props['LockfileVersion'])
| summarize max(LockfileVersion) by Detector;
customEvents
| where timestamp > timeRange
| where name == "LockfileVersion"
| extend Props = parse_json(customDimensions)
| extend Detector = Props['Detector'], LockfileVersion = toint(Props['LockfileVersion'])
| join kind=inner latestLockfileVersions on Detector
| where LockfileVersion > max_LockfileVersion
| project timestamp, Detector, LockfileVersion
```

**Comment by annaowens** [comment]
Closed. Monitors created.
