### ISSUE TITLE
Specific Integration test failure in Component Detection

### ISSUE THREAD

**Issue by bhansalirushabh** [microsoft/component-detection#56]
There are some intermittent test failures for integration test that are ran while merging the PR. Currently, these tests are not run while building locally since it relies on `componentdetection-verification` repo and specific OS environment. 

Action items.
1. Investigate if these tests can be run locally to debug them, and document the process.
2. Investigate root cause of the failures and fix it. 

Example failure:
https://github.com/microsoft/component-detection/runs/4970978052?check_suite_focus=true

**Comment by JamieMagee** [comment]
Closing this as the `componentdetection-verification` repository has been deprecated.
