### ISSUE TITLE
Update verification tests to verify the contract of `bcde-manifest.json`

### ISSUE THREAD

**Issue by melotic** [microsoft/component-detection#570]
With current refactoring in place to migrate from `Newtonsoft.Json` to `System.Test.Json` (see #231), we need to verify that `bcde-manifest.json` does not change its format.

One potential issue is the switching of naming from camcelCase to PascalCase (the default for `System.Text.Json`)

We can update the Verification tests CI step to also include a quick diff of the manifest, but we may need to sort the keys of the manifest using a tool like `jq`.

**Comment by JamieMagee** [comment]
We discussed this in #573 about adding a JSON schema, which would eliminate the need for these tests.
