### ISSUE TITLE
Create custom detectors

### ISSUE THREAD

**Issue by BlackyTheDruide** [microsoft/component-detection#632]
Hi,
 
currently we are developing a new Detector which we wanted to use as a Plugin. We started based on the idea provided by parameters like "AdditionalPluginDirectories" which suggested that it would be possible to use additional detectors. In the current version of the Component detectors there are no more parameters like them available. So is it still possible to create custom Detectors and provide them as kind of an plugin. If it is still possible, is there any documentation on which steps have to be taken so the Detector is working as expected?

**Comment by cobya** [comment]
Closing this as there hasn't been a follow up in ~1 year.
