### ISSUE TITLE
Support custom Feeds for pypi detection. 

### ISSUE THREAD

**Issue by RushabhBhansali** [microsoft/component-detection#661]
The current Pypi detector relys on package information on pypi.org feed. If customer is installing the python packages from custom feed from a different feed, this causes mismatch between detected and installed component versions. 

Request:
Add configuration to  support custom feed for pypi detector.

**Comment by RushabhBhansali** [comment]
Customer request that led to this finding: https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/2081241

**Comment by melotic** [comment]
duplicate of https://github.com/microsoft/component-detection/issues/415
