### ISSUE TITLE
Yarn v3+ support and performance

### ISSUE THREAD

**Issue by JamieMagee** [microsoft/component-detection#663]
Currently, Component Detection explicitly supports Yarn v1 and v2. We've had some customer reports of poor performance of our yarn detection.

Unfortunately, yarn support has gotten a little more complex recently. Yarn v1 is now considered [yarn 'classic'][1]. [Yarn 2 and 3][2] are a complete rewrite of yarn (and are sometimes called 'berry'). The lockfile version has incremented a lot.

| Yarn version       | lockfile version |
|--------------------|------------------|
| 1+                 | 1                |
| [`2.0.0-rc.2`][3]  | 2                |
| [`2.0.0-rc.5`][4]  | 3                |
| [`2.0.0-rc.15`][5] | 4                |
| [`3.1.0-rc.12`][6] | 5                |
| [`3.2.0-rc.12`][7] | 6                |
| [`4.0.0-rc.1`][8]  | 7                |
| [`4.0.0-rc.47`][9] | 8                |

We need to evaluate whether or not these lockfile changes are relevant to Component Detection, and the performance of our yarn detection for large projects in general.

[1]: https://classic.yarnpkg.com/lang/en/
[2]: https://yarnpkg.com/
[3]: https://github.com/yarnpkg/berry/commit/2f9e8073d15745f9d53e6b8b42fa9c81eb143d54
[4]: https://github.com/yarnpkg/berry/commit/b19708918a098f0453b0951f99123205c5b90c54
[5]: https://github.com/yarnpkg/berry/commit/aaa92b944673e05c9e3eeceedcd19ff98c480c82
[6]: https://github.com/yarnpkg/berry/commit/ccb0788bcb86005773fa06605d904f37db4c0a16
[7]: https://github.com/yarnpkg/berry/commit/d024a60e45018ec7e6fb3002f555c9be51f10d34
[8]: https://github.com/yarnpkg/berry/commit/1fbd616d346e71563b0712d7d75c645dd6cd812a
[9]: https://github.com/yarnpkg/berry/commit/21fcc792bf83825aa051c51c96cdc683ee85d20b

AB#2099326

**Comment by lvivski** [comment]
Hi @JamieMagee, I see you had several PRs already merged. Can Component Detection already be used with new Yarn versions?

**Comment by MLoughry** [comment]
As of testing it on Wednesday, I was still hitting the 6-minute timeout: https://outlookweb.visualstudio.com/Outlook%20Web/_build/results?buildId=1264416&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=3a7260a1-afda-5883-4f64-f6a170823839

**Comment by melotic** [comment]
> Hi @JamieMagee, I see you had several PRs already merged. Can Component Detection already be used with new Yarn versions?

This was for infrastructure to support V3. We do not have a specific detector for it yet.

**Comment by lvivski** [comment]
@melotic is there anything we can do to help with the development? Yarn@3 is over 3 times faster at our scale than v1. We would really like to be able to migrate to Yarn@3.

**Comment by melotic** [comment]
> @melotic is there anything we can do to help with the development? Yarn@3 is over 3 times faster at our scale than v1. We would really like to be able to migrate to Yarn@3.

We're currently planning work to prioritize this in this quarter

**Comment by lvivski** [comment]
Hey @melotic, is there any update on this issue?

**Comment by grvillic** [comment]
@lvivski - Yarn V3 was already merged and enabled by default in the detector. Please give it a go and let us know if you see any issues with it. See [release v4.0.8](https://github.com/microsoft/component-detection/releases/tag/v4.0.8).
