### ISSUE TITLE
component detection missing packages

### ISSUE THREAD

**Issue by wangzelin007** [microsoft/component-detection#73]
Hi component detection team,
Our public repo: [azure-cli](https://github.com/Azure/azure-cli) is using component detection in Azure DevOps pipelines.
in our repo, we have multiple setup.py file and reuqirment.txt file.
For example:
https://github.com/Azure/azure-cli/blob/dev/tools/setup.py
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/setup.py
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-telemetry/setup.py
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/setup.py
But component detection task only find the setup.py file in tools directory.
[component-detection.log](https://github.com/microsoft/component-detection/files/8174117/component-detection.log)

Thanks.

**Comment by melotic** [comment]
Superseded by #629
