### ISSUE TITLE
Support Central Package Management (CPM) for .NET components

### ISSUE THREAD

**Issue by jantache-microsoft** [microsoft/component-detection#743]
The files Packages.props and Directory.Packages.props used in CPM are not yet supported. As this functionality is now stable in .NET 6, it should be supported.

https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management

AB#2098999

**Comment by melotic** [comment]
Scanning those files will only tell us the direct dependencies. We cannot resolve transitive dependencies from a `Directory.Packages.props` file.
