### ISSUE TITLE
SPDX22SBOM Component type detecting unwanted info

### ISSUE THREAD

**Issue by sebasgomez238** [microsoft/component-detection#827]
#766 Introduced a change that opens up sbom's and parses their "Packages" section and they end up showing up as SPDX22SBOM components. The actual expected behavior is for SPDX22SBOM Components to just be SBOMs detected in the scan. This is affecting the https://github.com/microsoft/sbom-tool repo. Can we revert this change?

Created #825 for this.

AB#2110019

**Comment by melotic** [comment]
closed by #825
