### ISSUE TITLE
Do not mark build dependencies as dev dependencies

### ISSUE THREAD

**Issue by melotic** [microsoft/component-detection#844]
In the Rust CLI metadata detector, we're currently marking build dependencies as dev dependencies:

https://github.com/microsoft/component-detection/blob/7221fd43885352585da4480dd5c50486eb35f5b7/src/Microsoft.ComponentDetection.Detectors/rust/RustCliDetector.cs#L113

We should not include build dependencies, as these run code at compile time and can be a source of security vulnerabilities

AB#2111990

**Comment by annaowens** [comment]
Synced offline with @tevoinea to make sure build dependencies should receive alerts in CG. From Teo:

> "build deps _should_ be tracked. You can think of build dependencies sort of like a pre-compile script so a malicious build dep can do all sorts of nasty stuff like steal secrets/embed backdoors/etc. If the question is if they should be upgraded from dev dep to 'normal' dep, I think that could make sense."
