### ISSUE TITLE
Packages not being published to nuget.org

### ISSUE THREAD

**Issue by sebasgomez238** [microsoft/component-detection#854]
The repo is currently at version 4.0.5 but the latest version available on nuget.org is 3.7.0. Was this intentional or do the packages need to be published?

Thanks.

AB#2113145

**Comment by annaowens** [comment]
@sebasgomez238 Thanks for bringing this up! It looks like recent releases have failed to publish to NuGet. Will fix this and let you know when 4.0.5 is published 👍

**Comment by annaowens** [comment]
@sebasgomez238 Following up here--we fixed our releases to NuGet last week, latest updates should be there now.
