### ISSUE TITLE
Issue while mapping DependencyScope from maven dependency tree 

### ISSUE THREAD

**Issue by tarun06** [microsoft/component-detection#858]
Method name -> MavenParsingUtilities -> GetMavenComponentStringInfo  

On using below dependency with scope -> compile, in Maven Project, 

```
<dependency>
	<groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-java</artifactId>
	<version>4.8.0</version>
	<scope>compile</scope>
  </dependency> 
```

The SBOM throws an exception

**System.InvalidOperationException: Invalid scope ('linux-x86_64') found for 'io.netty:netty-transport-native-epoll:jar:4.1.87.Final:linux-x86_64' found in generated dependency graph**

More Info ->

Dependency tree generated using maven dependency CLI command 

`mvn dependency:tree -B -DoutputFile=bcde.mvndeps -DoutputType=text -f <SampleProjectPath>`, contains value linux-x86_64 and osx-x86_64 which further leads to an exception while parsing dependency Scope. 

Snapshot of Dependency tree 

```|  +- org.seleniumhq.selenium:selenium-remote-driver:jar:4.8.0:compile
|  |  +- com.beust:jcommander:jar:1.82:compile
|  |  +- io.netty:netty-buffer:jar:4.1.87.Final:compile
|  |  +- io.netty:netty-codec-http:jar:4.1.87.Final:compile
|  |  |  +- io.netty:netty-codec:jar:4.1.87.Final:compile
|  |  |  \- io.netty:netty-handler:jar:4.1.87.Final:compile
|  |  +- io.netty:netty-common:jar:4.1.87.Final:compile
|  |  +- io.netty:netty-transport-classes-epoll:jar:4.1.87.Final:compile
|  |  +- io.netty:netty-transport-classes-kqueue:jar:4.1.87.Final:compile
|  |  +- io.netty:netty-transport-native-epoll:jar:4.1.87.Final:linux-x86_64
|  |  +- io.netty:netty-transport-native-kqueue:jar:4.1.87.Final:osx-x86_64
|  |  +- io.netty:netty-transport-native-unix-common:jar:4.1.87.Final:compile
```

AB#2114682

**Comment by RushabhBhansali** [comment]
@tarun06 
When printing dependency tree on my end, below is the output
```
[INFO]    +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.60.Final:compile
[INFO]    |  \- io.netty:netty-transport-native-unix-common:jar:4.1.60.Final:compile
[INFO]    +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.60.Final:compile
```

as you can see there's compile at the end, so total there are six parts seperated by ":" This is handled correctly by maven detector.  I am not able to recreate maven cli output without "Compile" at the end.  Is there any truncation happening when you test ?

**Comment by RushabhBhansali** [comment]
upon investigating further, found that maven considers any value as a valid scope and replaces it with default. However, while printing dependency:tree, the invalid scope is preserved as is. 

Solution:
We will match CD behavior to maven's where we detect invalid scope as "Compile"
