### ISSUE TITLE
Parameter to control the summary display

### ISSUE THREAD

**Issue by sailro** [microsoft/component-detection#900]
In my case I have a custom application, which is using `Spectre.Console` and `component-detection` nugets to scan a folder. (so not running another executable, but directly controlling another `CommandApp<ScanCommand>` which is working as expected).

We have fine control over logging level but since you moved to `Spectre.Console` as well, `LogTabularOutput` is used to display a detection summary:

[    private void LogTabularOutput(ConcurrentDictionary<string, DetectorRunResult> providerElapsedTime, double totalElapsedTime)](https://github.com/microsoft/component-detection/blob/03a561ac9c9dd06170661c82e01859ed71c8a3af/src/Microsoft.ComponentDetection.Orchestrator/Services/DetectorProcessingService.cs#L303)

And rendering as is on the *default TextWriter (like Console.Out)* which is completely interfering with my application's output.

It is possible to hack a bit like using `AnsiConsole.AlternateScreen()` or redirecting `AnsiConsole.Profile.Out`, but that's not convenient or compatible with all use-cases (think of CI runs / redirected outputs).

So could we add a parameter to `ScanCommandSettings` like `NoSummary` to completely disable the rendering of this detection summary?

I can make a PR for that if you want.

Thanks!

AB#2123049

**Comment by melotic** [comment]
I think this is a good idea and shouldn't be too hard to implement.
