### ISSUE TITLE
On Linux cgmanifest.json files located under hidden directories are not found

### ISSUE THREAD

**Issue by ashbeitz** [microsoft/component-detection#97]
On Linux, if you store a cgmanifest.json file under a hidden directory (i.e. any directory that has a '.' prefix), then it will not be found by the component-detection tool.  On Windows, the cgmanifest.json file will be found.  Please fix this on Linux, so that it has parity with the behavior on Windows.

**Comment by cobya** [comment]
Closing this as the issue is for our internal version of the tool.
