### ISSUE TITLE
Investigate usage of pip install report for gathering Python dependencies

### ISSUE THREAD

**Issue by cobya** [microsoft/component-detection#980]
The [Installation Report](https://pip.pypa.io/en/stable/reference/installation-report/) generated by Pip may be sufficient to gather dependency information from Python setup files. May need to be used in conjunction with [pip inspect](https://pip.pypa.io/en/stable/reference/inspect-report/).

Originally discussed as part of #629 we should investigate whether or not the full dependency graph can be generated for Python ecosystems using this method.

AB#2141027

**Comment by cobya** [comment]
Example dry run commands using the pip command:

- For requirements.txt:
`pip install -r .\requirements.txt --dry-run --ignore-installed --report report-req.json`
- For setup.py:
`pip install -e . --dry-run --ignore-installed --report report.json`

**Comment by cobya** [comment]
Note that the report format version declared stable is only available in Pip > v23.0, this should be a conditional check before running this version of detection.

**Comment by cobya** [comment]
@edena-legit since you've been interested in Python detection previously, I'd love to have your input on the new `PipReport` detector and if you encounter any issues running it.

**Comment by kennylam91** [comment]
Hi @cobya , I'm having an issue with scanning a pip project right now. After investigating, I found that my pip version (20.0.2) is not compatible with the new PipReportComponentDetector. When I add flag '--DetectorArgs Pip=EnableIfDefaultOff', then the scan works. So my question is have the following condition check been implemented yet?
`Note that the report format version declared stable is only available in Pip > v23.0, this should be a conditional check before running this version of detection`
If not yet, should I always enable the flag to use the old detector? 
Thanks in advance.
